name: mudi_grocery_app
description: Mudi

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  firebase_core: 
  firebase_auth: ^0.6.6
  flutter_facebook_login: "3.0.0"
  google_sign_in: ^4.0.1
  cloud_firestore:
  firebase_storage: 



  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.5.0

flutter:

  uses-material-design: true

  assets:
      - assets/Asset_1.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
